notification_engine:
  host: 86.50.231.130
  port: 2379
  https: false
  polling_interval: 10

configuration_engine:
  host: 86.50.231.130
  port: 2379
  https: false

schema_parser: ecmwf
remote_schema: True
auth_type: etcd
username: root
key_file: /root/.aviso/key

listeners:
  - event: dissemination
    request:
      destination: SCL
    triggers:
      - type: echo