notification_engine:
  host: 86.50.231.130
  port: 2379
  https: false
  polling_interval: 10

configuration_engine:
  host: 86.50.231.130
  port: 2379
  https: false

schema_parser: ecmwf
remote_schema: True
auth_type: etcd
username: root
key_file: /root/.aviso/key

listeners:
  - event: dissemination
    request:
      destination: SCL
    triggers:
      - type: echo
listeners:
  - event: dissemination
    request:
      class: od
      destination: SCL
      target: E1
      date: 20000101
      domain: g
      expver: 9999
      step: 1
      stream: enfo
    triggers:
      - type: command
        working_dir: ~/aviso_configs
        command: ./restart_skinnywms.sh ${location}
      - type: log
        path: aviso.log